error: Add RESOURCE_ERROR_DEVICE_LOST error
Will be used to notify error when underlying device was removed
or no longer accessible, so therefore the corresponding resource
is not available.